# Generated by Django 6.0.4 on 2026-05-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablecoach',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='timetablecoach',
            name='status',
            field=models.CharField(default='Не оплачен', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coach',
            name='price',
            field=models.IntegerField(),
        ),
    ]
