# Generated by Django 6.0.4 on 2026-06-05 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach', to='FitnessApp.user'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='static/image/user/free-icon-user-9684504.png', upload_to='media/images/members/'),
        ),
    ]
