# Generated by Django 6.0.4 on 2026-05-07 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0002_timetablecoach_amount_timetablecoach_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetPreview',
        ),
    ]
