# Generated by Django 6.0.4 on 2026-06-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0002_alter_coach_user_alter_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='media/images/members/free-icon-user-9684504.png', upload_to='media/images/members/'),
        ),
    ]
