# Generated by Django 6.0.4 on 2026-06-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0003_alter_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcard',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
