# Generated by Django 6.0.4 on 2026-05-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0004_shopcategory_shopitem_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='img',
            field=models.ImageField(default='1321', upload_to='media/images/shop/'),
            preserve_default=False,
        ),
    ]
