# Generated by Django 6.0.4 on 2026-05-08 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0005_shopitem_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='price',
            field=models.DecimalField(decimal_places=2, default='12', max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShopItemPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemPayments', to='FitnessApp.shopitem')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberPayments', to='FitnessApp.member')),
            ],
        ),
    ]
