# Generated by Django 6.0.4 on 2026-05-09 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0006_basket_price_shopitempayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ID платежа в системе шлюза')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Сумма платежа')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('succeeded', 'Успешно завершен'), ('canceled', 'Отменен'), ('refunded', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='FitnessApp.shopitem', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='ShopItemPayment',
        ),
    ]
